FROM golang:alpine AS builder
ENV GOOS=linux \
    GOARCH=amd64

WORKDIR /build

COPY go.mod .
RUN go mod tidy

COPY . .
RUN go build -mod=mod -o main .

FROM alpine

WORKDIR /dist
ARG TOKEN
ARG APP_ID
ARG FIREBASE_CONFIG
ARG FIREBASE_PROJECT_ID
ARG DATADOG_API_KEY
ENV PRODUCTION=TRUE
ENV TOKEN=$TOKEN
ENV FIREBASE_CONFIG=$FIREBASE_CONFIG
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV DATADOG_API_KEY=$DATADOG_API_KEY
ENV APP_ID=$APP_ID

COPY --from=builder /build/main /dist
COPY --from=builder /build/resources /dist/resources

ENTRYPOINT ./main 