version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     - run: echo "$GITLABPASSWORD" | docker login registry.gitlab.com --username acnologla --password-stdin
     - run: docker build -t registry.gitlab.com/acnologla/asura --build-arg TOKEN="$TOKEN" --build-arg FIREBASE_CONFIG="$FIREBASE_CONFIG" --build-arg FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" --build-arg DATADOG_API_KEY="$DATADOG_API_KEY" .
     - run: docker push registry.gitlab.com/acnologla/asura