version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     - run: echo "$GITLABPASSWORD" | docker login registry.gitlab.com --username acnologla --password-stdin
     - run: docker build --build-arg TOKEN=$TOKEN --build-arg FIREBASE_CONFIG=$FIREBASE_CONFIG --build-arg FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID --build-arg DATADOG_API_KEY=$DATADOG_API_KEY . -t registry.gitlab.com/acnologla/asura
     - run: docker push registry.gitlab.com/acnologla/asura