version: 2.1
jobs:
    Unit-test:
      docker:
         - image: 'circleci/golang:1.14'
      steps:
         - checkout
         - run:
            name: Unit test
            command: go test ./test
    Build-and-deploy:
      resource_class: arm.medium
      docker:
         - image: 'jdrouet/docker-with-buildx:stable'
      steps:
         - checkout
         - setup_remote_docker:
            version: 18.09.3
         - run: docker run --privileged --rm tonistiigi/binfmt --install all
         - run:
            name: Docker build and deploy
            command: |
                echo "$GITLABPASSWORD" | docker login registry.gitlab.com --username acnologla --password-stdin
                docker build -t registry.gitlab.com/acnologla/asura --build-arg TOKEN="$TOKEN" --build-arg FIREBASE_CONFIG="$FIREBASE_CONFIG" --build-arg FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" --build-arg TOP_TOKEN="$TOP_TOKEN" --build-arg DATADOG_API_KEY="$DATADOG_API_KEY" .
                docker push registry.gitlab.com/acnologla/asura
      

workflows:
    version: 2
    test_and_build:
      jobs:
         - Unit-test
         - Build-and-deploy: 
            filters:
               branches:
                  only: master
