version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     - run: echo "$GITLABPASSWORD" | docker login registry.gitlab.com --username acnologla --password-stdin
     - run: docker build -t registry.gitlab.com/acnologla/asura .
     - run: docker push registry.gitlab.com/acnologla/asura